[tool.poetry]
name = "routingpy"
version = "0.3.3"
description = "One lib to route them all."
authors = ["Nils Nolde <nils@gis-ops.com>", "Tim Ellersiek <tim@gis-ops.com>"]
license = "Apache2"
readme = 'README.rst'

[tool.poetry.dependencies]
python = "^3.7.0"
requests = "^2.20.0"
# For the Jupyter notebooks:
pandas = {version = "^1.1.0", optional = true}
shapely = {version = "^1.7.0", optional = true}
ipykernel = {version = "^5.3.4", optional = true}
matplotlib = {version = "^3.4.1", optional = true}
contextily = {version = "^1.1.0", optional = true}
geopandas = {version = "^0.8.2", optional = true}


[tool.poetry.dev-dependencies]
sphinx = "^3.0.0"
sphinx-rtd-theme = "~0.5.0"
coveralls = "^2.0.0"
nose = "^1.3.0"
responses = "^0.10.0"
coverage = "^5.0.4"
pre-commit = "^2.7.1"
flake8 = "^3.9.1"
black = "^21.6b0"

[tool.poetry.extras]
notebooks = ["pandas", "shapely", "ipykernel", "geopandas", "contextily", "matplotlib"]

[tool.black]
line-length = 105
exclude = '''
/(
    \.git
  | \.venv
  | dist
  | build
)/
'''

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
