[tool.poetry]
name = "routingpy"
version = "0.3.0"
description = "One lib to route them all."
authors = ["Nils Nolde <nils@gis-ops.com>", "Tim Ellersiek <tim@gis-ops.com>"]
license = "Apache2"
readme = 'README.rst'

[tool.poetry.dependencies]
python = "^3.6.1"
requests = "^2.0.0"
pandas = {version = "^1.1.0", optional = true}
folium = {version = "^0.11.0", optional = true}
shapely = {version = "^1.7.0", optional = true}
ipykernel = {version = "^5.3.4", optional = true}

[tool.poetry.dev-dependencies]
sphinx = "^3.0.0"
sphinx-rtd-theme = "~0.5.0"
coveralls = "^2.0.0"
nose = "^1.3.0"
yapf = "^0.30.0"
responses = "^0.10.0"
tox = "^3.14.6"
coverage = "^5.0.4"

[tool.poetry.extras]
notebooks = ["pandas", "folium", "shapely", "ipykernel"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
