[tool.poetry]
name = "routingpy"
version = "0.2.4"
description = "One lib to route them all."
authors = ["Nils Nolde <nils@gis-ops.com>", "Tim Ellersiek <tim@gis-ops.com>"]
license = "Apache2"

[tool.poetry.dependencies]
python = "^3.5"
requests = "^2.0.0"

[tool.poetry.dev-dependencies]
sphinx = "^2.0.0"
sphinx-rtd-theme = "~0.4.3"
coveralls = "^1.7.0"
nose = "^1.3.0"
yapf = "^0.26.0"
responses = "^0.10.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
